package kz.btokmyrza.calorytracker.navigation

object Route {
    const val ONBOARDING_WELCOME = "ONBOARDING_WELCOME"
    const val ONBOARDING_GENDER = "ONBOARDING_GENDER"
    const val ONBOARDING_AGE = "ONBOARDING_AGE"
    const val ONBOARDING_HEIGHT = "ONBOARDING_HEIGHT"
    const val ONBOARDING_WEIGHT = "ONBOARDING_WEIGHT"
    const val ONBOARDING_ACTIVITY_LEVEL = "ONBOARDING_ACTIVITY_LEVEL"
    const val ONBOARDING_NUTRIENT_GOAL = "ONBOARDING_NUTRIENT_GOAL"
    const val ONBOARDING_GOAL = "ONBOARDING_GOAL"

    const val TRACKER_OVERVIEW = "TRACKER_OVERVIEW"
    const val TRACKER_SEARCH = "TRACKER_SEARCH"
    const val TRACKER_SEARCH_ARG_MEAL_NAME = "TRACKER_SEARCH_ARG_MEAL_NAME"
    const val TRACKER_SEARCH_ARG_DAY = "TRACKER_SEARCH_ARG_DAY"
    const val TRACKER_SEARCH_ARG_MONTH = "TRACKER_SEARCH_ARG_MONTH"
    const val TRACKER_SEARCH_ARG_YEAR = "TRACKER_SEARCH_ARG_YEAR"
    const val TRACKER_SEARCH_ARGS = "/{$TRACKER_SEARCH_ARG_MEAL_NAME}" +
            "/{$TRACKER_SEARCH_ARG_DAY}" +
            "/{$TRACKER_SEARCH_ARG_MONTH}" +
            "/{$TRACKER_SEARCH_ARG_YEAR}"
}