package kz.btokmyrza.calorytracker.core.navigation

object Route {
    const val ONBOARDING_WELCOME = "ONBOARDING_WELCOME"
    const val ONBOARDING_GENDER = "ONBOARDING_GENDER"
    const val ONBOARDING_AGE = "ONBOARDING_AGE"
    const val ONBOARDING_HEIGHT = "ONBOARDING_HEIGHT"
    const val ONBOARDING_WEIGHT = "ONBOARDING_WEIGHT"
    const val ONBOARDING_ACTIVITY_LEVEL = "ONBOARDING_ACTIVITY_LEVEL"
    const val ONBOARDING_NUTRIENT_GOAL = "ONBOARDING_NUTRIENT_GOAL"
    const val ONBOARDING_GOAL = "ONBOARDING_GOAL"

    const val TRACKER_OVERVIEW = "TRACKER_OVERVIEW"
    const val TRACKER_SEARCH = "TRACKER_SEARCH"
}